### ISSUE TITLE
Unable to download Latest latest version

### ISSUE THREAD

**Issue by dbuskariol** [mangerlahn/Latest#10]
I can't seem to find a download link to Latest anywhere as there are no releases and the GH Pages site just redirects back here

**Comment by mangerlahn** [comment]
That’s because there is no ready to use app yet. I wanted to provide an app, when the updater framework is included, so that no one has to check this page for new updates. 
I just have not come around to do that until now. I try to do that soon :)

If you have Xcode installed, you can build the app yourself for now

**Comment by mangerlahn** [comment]
Closing as a duplicate of #7

**Comment by dbuskariol** [comment]
Awesome, thanks!
