### ISSUE TITLE
Translating the name of the application

### ISSUE THREAD

**Issue by milotype** [mangerlahn/Latest#151]
Do you accept literal translations for your application's name **Latest**?

**Comment by mangerlahn** [comment]
Thats a good question! But first of all, thank you so much for your translation! :) 

I am a native German speaker, most Apple apps for iOS and macOS with generic names (Photos, Messages, Music, Maps) are translated, however some others are not (Finder, Mail, Home, Health). I think it depends on whether there is a proper name for the app within the german language. Not sure if its the same way for Croatian. So I'd like to avoid forcing a translated name of the app if it does not fit. But if `Latest` sounds _off_ and there is a good translation, I am happy to accept it :)

**Comment by mangerlahn** [comment]
![Slika zaslona 2022-04-11 u 22 46 40](https://user-images.githubusercontent.com/11056766/162829217-f0e9c989-d608-4ce2-8911-266dcb14747c.png)

**Comment by mangerlahn** [comment]
That's even better :D 

I can't speak for Croatian, but in German, as you know, English (or English sounding) words are getting more common. To me it would feel like forcing a German translation onto a word that is fine for the German language. 

But that may be different for other languages like French or Croatian, so I have zero problems with translating the app name there :) 
If I spelled the name correctly in the screenshot, I will go and create a new component on Weblate for that, because unfortunately this info has to be stored in a separate file..

**Comment by mangerlahn** [comment]
Ok, I added the component and hope I added the correct text 😅

Stuff like version and "Open Latest" do not need to be translated. I just simulated a Croatian locale without switching the system language, that's why there are some missing translations in the screenshot
