### ISSUE TITLE
Incorrect parsing of latest app version

### ISSUE THREAD

**Issue by rodrigobdz** [mangerlahn/Latest#18]
Latest is showing that there is an update available for [Texpad](https://www.texpad.com/) but I'm using the latest version. See screenshots below.

[Latest](https://github.com/mangerlahn/Latest) version: 0.3.1

- Latest screenshot showing an update available for Texpad:

![image](https://user-images.githubusercontent.com/14152377/41191736-0c49b438-6bf4-11e8-82cd-82fd670b4905.png)

- Texpad screenshot with version

![image](https://user-images.githubusercontent.com/14152377/41191731-0729100c-6bf4-11e8-955e-40bc31e9acd3.png)

**Comment by mangerlahn** [comment]
Thanks for writing that down! I am a Texpad User as well and currently try to refactor the current behavior. I currently get the most current version by date, but Texpad messes that up. The best thing to do is to implement way better version checking. But developers sometimes change their version format, so *some* apps will probably always fall throug..
However I can assure you Texpad will be fixed by this change :)

**Comment by mangerlahn** [comment]
I addressed this issue in ec515a06e44a571e074ed46d44b9e60d03f213e3
