### ISSUE TITLE
App list is blank...

### ISSUE THREAD

**Issue by jeff3820** [mangerlahn/Latest#206]
I downloaded Latest to my Download folder, unzipped it and ran the Latest.app file. The list of apps is blank??! Is this because I ran Latest in the Download folder? Does it have to run in the Applications folder??

Is there an uninstall process or just delete the Latest.app?

**Comment by mangerlahn** [comment]
Hi Jeff, 

By default, the list of apps should be empty if there are no updates available. If you wish, you can show a list of all apps by selecting View > Show Installed Apps in the menu bar. It should be fine to run Latest from the Downloads folder. 

To uninstall the App, you can just delete Latest.app :)

**Comment by tepehuani** [comment]
I came here because I had the same concern - I think mostly made worse by the "Select an app from the list to read its release notes." text on the right, which implies there should be something there "normally." Might improve first launch experience to add a second sentence pointing out that this view option exists.

**Comment by mangerlahn** [comment]
Fixed with 34d0233
