### ISSUE TITLE
com.max-langer.latest

### ISSUE THREAD

**Issue by carlodrift** [mangerlahn/Latest#248]
![image](https://user-images.githubusercontent.com/30211659/220199958-02ea462f-a978-4c2d-97a7-973f99cd8216.png)

**Latest** version: 0.9

**Comment by mangerlahn** [comment]
Is this by any chance an app you downloaded via TestFlight?

**Comment by carlodrift** [comment]
No, a pkg file

**Comment by YakshaContador** [comment]
Hello, same problems for me since the last update : on some independent games, which sounds normal, but also on well known apps libre Calibre or FileZilla. See below : 
<img width="284" alt="Capture d’écran 2023-02-23 à 16 58 10" src="https://user-images.githubusercontent.com/89033315/220961409-590926ac-eced-4374-ba94-ad57047fb233.png">
<img width="294" alt="Capture d’écran 2023-02-23 à 16 57 01" src="https://user-images.githubusercontent.com/89033315/220961422-8fe112ab-7893-49c8-a41e-a42e2c7afbb0.png">

**Comment by uncompromise** [comment]
Confirming that I am having this same issue on my M1 MacBook Air (recently purchased) running Ventura 13.4.1, but not on my 2014 MBP running Big Sur 11.7.8. So it may be an issue with the OS?

**Comment by mangerlahn** [comment]
The issue here is that error messages are not displayed properly and therefore are rather unhelpful. Fixed in a395086a70a6df1fec850f043dd27c9d3748f5ab
