### ISSUE TITLE
Open apps button opens ALL sparkle apps

### ISSUE THREAD

**Issue by Wdavery** [mangerlahn/Latest#26]
The button in the top right corner that used to open all apps with updates, now opens all apps that are using sparkle. 
Although it was quite the show, and I was pleasantly surprised at how well my computer handled opening 54 apps simultaneously, I definitely won't be clicking that again.

**Comment by mangerlahn** [comment]
Wow, I am super sorry for that!

**Comment by Wdavery** [comment]
Haha, hopefully I caught it before other people run into it too.

As an aside, I think the icon for that function may not be super clear.
To me it looks like a "grid mode" option for sorting.

It might be better to change to a text option of "Update All". 
<img width="969" alt="Update All" src="https://user-images.githubusercontent.com/12989893/44218789-75bf7900-a148-11e8-9c7d-33dbc521286b.png">

**Comment by mangerlahn** [comment]
Yeah, thank you so much for reporting fast! I just uploaded a new binary that fixes this particular problem, as it could crash peoples machines..

#27 will be fixed tomorrow in 0.4.1. I just want to make sure I did not mess up anything else 🤪

I don't like the icon either. To move that into the table view seems like a good idea, I just have to see where I put that if the sections are not visible.
Long term, I just want to update the apps right from Latest, instead of opening them. I just have to see how to manage that..

**Comment by mangerlahn** [comment]
If you have time, feel free to download the new version to verify that this is fixed. You can close this issue then.

**Comment by mangerlahn** [comment]
Ha, made you click that button again 😅

No seriously, thanks again!

**Comment by Wdavery** [comment]
Not going to lie, I was a bit nervous. Love the quick fix though!
