### ISSUE TITLE
Apps Not Supported By Latest

### ISSUE THREAD

**Issue by evanlrndlt** [mangerlahn/Latest#260]
Hi, my Latest can't support any app that is downloaded before I download Latest, which those apps are not from the App Store. Apps like Notion, Avast Security, Visual Studio, VSCode, MuseScore, Zoom, etc. And my Latest can support apps that are downloaded after I download Latest, which those apps are also not from the App Store. Thanks so much!!!

**Comment by mangerlahn** [comment]
It should not make a difference whether apps were downloaded before or after Latest. Several apps are not supported. I hope to extend support soon, but with the approach Latest is using, it will never support _every_ app. A major step would be to add Homebrew cask support (#262). This would add support for some of the apps you have listed. Otherwise, this is is a duplicate of #19, so closing it for now :)

**Comment by evanlrndlt** [comment]
Thanks so much!
