### ISSUE TITLE
not showing all apps

### ISSUE THREAD

**Issue by ghost** [mangerlahn/Latest#78]
When I go to View>Show Installed Apps and/or View>Show Ignored Apps it only shows me a few of the apps I have installed with most of them missing. I am on macOS Catalina.

**Comment by gottabeleGIT** [comment]
UPDATE: I opened the app today, and now no apps show up. I've even uninstalled and reinstalled the app.

**Comment by gingerbeardman** [comment]
If no apps show, then no updates are available.

**Comment by gottabeleGIT** [comment]
Even if show all apps is on?

**Comment by gingerbeardman** [comment]
With that option checked it should show apps that it recognises that are up-to-date (it does for me).

![Screen shot 2020-01-06 at 14 06 02](https://user-images.githubusercontent.com/49612/71822795-b4333c00-308d-11ea-9546-490cb4308758.png)

**Comment by gottabeleGIT** [comment]
Ok, because I'm concerned that it doesn't detect any of my apps. When I click check for updates, the "circle progress" thing doesn't appear after my apps disappeared from latest.

**Comment by gingerbeardman** [comment]
As I understand it: the app checks only apps that were in the list after an update, some time later it will do a full scan.

**Comment by gottabeleGIT** [comment]
Ok, so this is expected behavior for this application?

**Comment by gingerbeardman** [comment]
I believe so

**Comment by gottabeleGIT** [comment]
Alright, so can I change this issue to a feature request? Because the current behavior is a little confusing. When a user clicks "Show Installed Apps" it should show all installed apps on the Mac, even if they are up-to-date. An example of this behavior can be found in the application "MacUpdater" where there is a separate tab for "All Apps" even if they are already up-to-date, and "Outdated Apps."

**Comment by gingerbeardman** [comment]
> When a user clicks "Show Installed Apps" it should show all installed apps on the Mac, even if they are up-to-date. 

It should do this, see my screen grab above.

If you're not seeing that something is wrong with your setup.

**Comment by gottabeleGIT** [comment]
That’s what I thought. However, I’m unable to get it to work. I’ve tried uninstalling and reinstalling the application too.

**Comment by gingerbeardman** [comment]
Try using [AppCleaner](https://freemacsoft.net/appcleaner/)

**Comment by gottabeleGIT** [comment]
Yes, I have tried that as well as the `brew cask zap` command

**Comment by gottabeleGIT** [comment]
The thing is, MacUpdater had no issues detecting my installed apps, so I don’t think it’s the setup.

**Comment by gingerbeardman** [comment]
These are two different apps, we're only talking about how Latest is installed and setup. There's a problem with it on your system, as it works correctly on mine.

**Comment by gottabeleGIT** [comment]
Right, my apologies. I will keep trying to troubleshoot the issue. Thanks for your help.

**Comment by gottabeleGIT** [comment]
So, it just decided to start showing my apps now. However, it still only shows some apps with most of them missing.

**Comment by mangerlahn** [comment]
Hi @gottabeleGIT, sorry for my super late response. 
Latest currently only shows apps which _can_ be updated by the app. Thats why system apps like Reminders or Notes do not show up. If you use any third party software obtained outside the Mac App Store that does use anything other than Sparkle as its updater, I won't show it. 
Just because you couldn't do anything with it. 

However I unterstand the confusion since the section title is "Installed Apps", similar to the menu command. So something needs to be fixed here. Either we improve the wording or we just show all apps. They'd need a special look however. They could be greyed out for example, since we can't show any release notes for them and so on..

I see arguments on both sides. People instinctively look for certain apps in the list and just can't find them. On the other side we introduce some amount of "useless clutter" to the list since nothing can be done with these apps inside Latest..

**Comment by mangerlahn** [comment]
Also thanks @gingerbeardman for helping out quickly :)

**Comment by mcmz** [comment]
> They'd need a special look however. They could be greyed out for example, since we can't show any release notes for them and so on..

That would be a good idea to make the GUI less confusing.

Besides, i have/had the same problem here. At first no apps showed up at all. Then i figured out, that the /Application index is based on the »Spotlight« index (maybe worth mentioning in the Readme?). Mine was deactivated at all. After the following commands (maybe »Onyx« can help too) …
`
sudo mdutil -i off /
sudo rm -rf /.Spotlight*
sudo rm -rf /.metadata_never_index
sudo mdutil -i on /
sudo mdutil -E /
`
1) https://apple.stackexchange.com/questions/62715/applications-dont-show-up-in-spotlight
2) https://apple.stackexchange.com/questions/24401/spotlight-reports-indexing-and-searching-disabled-in-lion?rq=1

… the »Latest« index showed me at least some Apps. 30% or so, whilst »Spotlight« had indexed all /Applications by now..

Nevertheless »AppCleaner« gives me a complete list of all my /Applications, even with »Spotlight« deactivated. 

Maybe it is possible to have a less sophisticated /Application index fallback or a setting for users with deactivated »Spotlight«.

NB: The following command returns 20 items (75 apps are installed):
`mdfind -onlyin /Applications/ | wc -l `
'kMDItemKind == "Application"' commands returned 0.

»Latest« lists only 10 apps out of these in its view. Dunno what could cause the problem, tested within two OSX installations (High Sierra and Mojave).

**Comment by mangerlahn** [comment]
Thank you very much for your explanations! I created two new issues which contain the requests I made out of your post. #95  and #96.
